### ISSUE TITLE
ccache setup

### ISSUE THREAD

**Issue by lehmancurtis147** [PizzaG/A-Team_android-BuildMenu#1]
[In this script.](https://github.com/PizzaG/A-Team_Android-BuildMenu/blob/main/RecoveryBuildScripts/Build-beyond0qlte.sh) You would be rebuilding the ccache on every new build. That makes the ccache all but useless. Instead try a conditional expression.
 ```bash
if [ -e <path to ccache directory> ]; then
    echo -e "ccache is already setup
else
    ccache -M 50G
    export USE_CCACHE=1
fi
```

**Comment by PizzaG** [comment]
this has been very slightly modified and added into the build scripts and will be updated on here soon.  Thanks for the tip, much appreciated
